language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true

services:
  - mysql

install:
  - travis_retry composer install --no-interaction --prefer-source
  - chmod -R 777 app/storage
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS laravel-rest-cms;' -uroot -proot
  - composer self-update

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; else vendor/bin/phpunit --no-coverage; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi