language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7
    - php: hhvm

services:
  - mysql

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS laravel-rest-cms;' -uroot
  - composer self-update

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; else vendor/bin/phpunit --no-coverage; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi