language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true

services:
  - mysql

install:
  - composer self-update
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - travis_retry composer install --no-interaction --prefer-source
  - chmod -R 777 storage
  - travis/install-nginx.sh

addons:
  apt:
    packages:
      - nginx
      - realpath

before_script:
  - mv .env.travis .env
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database IF NOT EXISTS `laravel-rest-cms`;' -uroot -proot
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv

after_script:
  - php vendor/bin/coveralls -v

script:
  - mkdir -p build/logs
  - if [ "$COLLECT_COVERAGE" == "true" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --no-coverage; fi

after_failure: 
  - "cat /home/travis/build/ddimaria/laravel-rest-cms/npm-debug.log"
